<?php
echo "PHP_SELF = ".$_SERVER['PHP_SELF'];
echo "<br>";
echo "SCRIPT_NAME = ".$_SERVER['SCRIPT_NAME'];
echo "<br>";
echo "SERVER_NAME = ".$_SERVER['SERVER_NAME'];
echo "<br>";
echo "SERVER_ADDR = ".$_SERVER['SERVER_ADDR'];
echo "<br>";
echo "SERVER_SOFTWARE = ".$_SERVER['SERVER_SOFTWARE'];
echo "<br>";
echo "REQUEST_METHOD = ".$_SERVER['REQUEST_METHOD'];
echo "<br>";
echo "HTTP_ACCEPT = ".$_SERVER['HTTP_ACCEPT'];
echo "<br>";
echo "HTTP_HOST = ".$_SERVER['HTTP_HOST'];
echo "<br>";
echo "REMOTE_ADDR = ".$_SERVER['REMOTE_ADDR'];
echo "<br>";
echo "SERVER_PORT = ".$_SERVER['SERVER_PORT'];
echo "<br>";
echo "SERVER_SIGNATURE = ".$_SERVER['SERVER_SIGNATURE'];
echo "<br>";
echo "HTTP_USER_AGENT = ".$_SERVER['HTTP_USER_AGENT'];
